### ISSUE TITLE
How do PostMessage and DeleteMessage work in the Message component?

### ISSUE THREAD

**Issue by SHxKM** [gtalarico/django-vue-template#10]
Hi, 

I know this may not be an "issue" per-se, but I can't figure out the following. In the [Messages.vue](https://github.com/gtalarico/django-vue-template/blob/master/src/components/Messages.vue) file, we have the following code:

```
postMessage() {
      const payload = { subject: this.subject, body: this.msgBody };
      this.$backend.$postMessage(payload).then(() => {
        this.msgBody = ""
        this.subject = ""
        this.fetchMessages();
      });
    },
    deleteMsg(msgId) {
        this.$backend.$deleteMessage(msgId).then(() => {
            this.messages = this.messages.filter(m => m.pk !== msgId)
            this.fetchMessages();
        });
    }
  }
```

This to me looks a lot like "magic" because I don't see anywhere in our `backend` methods that correspond to "creating" or 'deleting" a message such as we see in the Django REST framework tutorial.

**Comment by SHxKM** [comment]
I've figured `ModelViewSet` introduces these methods.

**Comment by gtalarico** [comment]
> I've figured ModelViewSet introduces these methods.

Exaclty

Front End calls are consolidated here:
https://github.com/gtalarico/django-vue-template/blob/master/src/backend.js#L23

Backend Routing is automatically created by Django RestFramework.
The line below creates a `/messages` endpoint. 
https://github.com/gtalarico/django-vue-template/blob/master/backend/urls.py#L14

DjangoRest ViewSets automatically creates all the rest methods (eg POST, DELETE, etc)
http://www.django-rest-framework.org/api-guide/viewsets/#viewset

djangorest is pure magic :)
