### ISSUE TITLE
improvement suggestion: use named paths

### ISSUE THREAD

**Issue by SHxKM** [gtalarico/django-vue-template#11]
I wondered in [App.vue](https://github.com/gtalarico/django-vue-template/blob/master/src/App.vue), what happens if we decide to change the `path` of a nav item?

```
<div id="nav">
      <router-link to="/">Vue</router-link> |
      <router-link to="/messages">Django Rest</router-link>
</div>
```

I think it would be better  to use a named path, like this:

```
<div id="nav">
    <router-link :to="{ name: 'home' }">Vue</router-link> |
    <router-link :to="{ name: 'messages' }">Django Rest</router-link>
</div>
```

**Comment by SHxKM** [comment]
Maybe I can create a (first-ever personal) PR for this?

**Comment by gtalarico** [comment]
Happ to merge that

**Comment by SHxKM** [comment]
Cool. I’ll get to this later as I’m not sure what the correct workflow for that is.

**Comment by SHxKM** [comment]
Hope I didn't botch it...let me know if I did something wrong/if anything could be done bettter.

**Comment by gtalarico** [comment]
Looks good, thanks!
