### ISSUE TITLE
Heroku App Server error on /api/model

### ISSUE THREAD

**Issue by zzzint** [gtalarico/django-vue-template#18]
When trying to view MYHEROKUURL/api I'm getting a bad request / server error, and I've noticed I get it on your live demo as well.

**Comment by gtalarico** [comment]
I think the problem is `yarn build` is wiping the static files from `collectstatic`.
That would also explains why it runs fine on dev mode but fails in production. 
I will look into this.

**Comment by zzzint** [comment]
I ended up fixing it by using the Heroku database locally and running make
migrations / migrate there.

**Comment by gtalarico** [comment]
I was having the same issue but mine were cased missing staticfiles to serve restframework files.

My buildpacks were setup incorrectly, so yarn build was wiping django's staticfiles.

node/yarn needs to go first and then the django/collectstatic. This fixed it for me.

```
heroku buildpacks
```
And to correct:
```
heroku buildpacks:clear
heroku buildpacks:add --index 1 heroku/nodejs
heroku buildpacks:add --index 2 heroku/python
```
