### ISSUE TITLE
how to deploy pure with nginx and wsgi?

### ISSUE THREAD

**Issue by guoliangli123** [gtalarico/django-vue-template#19]
I see the document write to build with Heroku Server,but I do not know how to use it.Can I depoly with nginx?

**Comment by gtalarico** [comment]
You should be able to serve this template using nginx, but I am not familiar with nginx configs.
I would suggest you look for other resources on configuring nginx and try to integrate it.
https://vladikk.com/2013/09/12/serving-flask-with-nginx-on-ubuntu/

**Comment by gtalarico** [comment]
Feel free to follow up on your question here, but I will close the issue for now since nginx config is outside the scope of this project.
