### ISSUE TITLE
Application Error on Heroku

### ISSUE THREAD

**Issue by SHxKM** [gtalarico/django-vue-template#23]
Was the app taken down from Heroku? I'm still using it as reference, especially now that I want to combine Nuxt + Django on Heroku..

**Comment by gtalarico** [comment]
Thanks for pointing this out.
It is supposed to be up - I will look into this

**Comment by gtalarico** [comment]
Seems to be up now - not sure what the cause was
https://django-vue-template-demo.herokuapp.com

![image](https://user-images.githubusercontent.com/9513968/55350247-79520700-5470-11e9-9ea7-5e0d816e5a18.png)

**Comment by SHxKM** [comment]
Glad to see it's sorted.


P.S.: Your project helped me with making this one: https://django-nuxt-ssr.herokuapp.com/ (on free dynos as well so might take some time to load)
