### ISSUE TITLE
Authentication and Permissions

### ISSUE THREAD

**Issue by schantanu** [gtalarico/django-vue-template#4]
I am still learning DRF and Vue, so can you add how a basic authentication and permissions can work? I am able to post and delete via the rest api, but unable to do via Vue. To give a test case, I want to AllowAny to post, but users needs to be authenticated to edit/delete.

**Comment by gtalarico** [comment]
Hi. Thanks for the suggestion.
At this time I want to keep the template small and authentication is out of that scope. 
I would suggest you look into Django rest auth as it provides several easy to implement auth schemas:
https://github.com/Tivix/django-rest-auth
Cheera
