### ISSUE TITLE
ImproperlyConfigured: Cannot import 'api'.

### ISSUE THREAD

**Issue by eldo-greshard** [gtalarico/django-vue-template#76]
Just follow your readme, and it's throw an error 

django.core.exceptions.ImproperlyConfigured: Cannot import 'api'. Check that 'backend.api.apps.AppConfig.name' is correct.

while i ran 
python manage.py migrate

**Comment by 10zinten** [comment]
I think the template is for django 2. I also got the same error with django 3 and fixed it with using django 2.
