### ISSUE TITLE
Can we integrate another apps in django ?

### ISSUE THREAD

**Issue by AnasR7** [gtalarico/django-vue-template#8]
Hello Im New in django, and i like somuch for your template ! :heart: 

i just wanna ask something, if i make another apps in django-vue-template
with `startapp` and how to integrate with backend/api section?, bcuz when i create new apps in django they are in outside backend folder...

thanks.
best regards...

sorry for mybad english.

**Comment by gtalarico** [comment]
You cana use startapp and just keep the apps inside the `backend` folder. 
There is already an app in there called "api" so you can add just copy it and modify as needed.
You will just need to update your imports, routes, and settings as needed.

Current setup:

|  Path                   | Description |
--------------------|--------------|
| `/`                        | Root |
| `/backend`          | Django Project|
| `/backend/api`   | Django App |


Example with more Apps:

|  Path                   | Description |
--------------------|--------------|
| `/`                        | Root |
| `/backend`          | Django Project|
| `/backend/auth`   | Django App |
| `/backend/api`   | Django App |
| `/backend/anotherapp`   | Django App |

**Comment by AnasR7** [comment]
thanks !
